### ISSUE TITLE
utilities.preProc as preProc module not found

### ISSUE THREAD

**Issue by SundareshPrasanna** [abtpst/Doc2Vec#1]
Hi I am having issues importing utilities.preProc as it is showing that the module does not exist. Can you please guide me on how to resolve this ?? thanks!!

**Comment by abtpst** [comment]
ok, found the problem. i'll push some updates

**Comment by abtpst** [comment]
so the issue appears because of some restructuring i did. try cloning the following new version of doc2vec and word2vec

https://github.com/abtpst/WordVectors

and you should be good
